export const POSTS = [
  {
    slug: "/blog/home-services-scenario",
    title: "How a home services company stopped losing after-hours jobs to the competition",
    dek: "An illustrative Maxera scenario: how a 60-second AI lead response system, running 24/7, flipped the booked-job rate at a typical home services company.",
    category: "Field notes",
    readTime: "6 min",
    date: "May 13, 2026",
    published: true,
  },
  {
    slug: "/blog/ecommerce-scenario",
    title: "How a mid-market ecommerce brand got its evenings back with AI",
    dek: "An illustrative scenario showing what a typical Maxera engagement looks like inside a mid-market ecommerce operations team: customer service co-pilot, inventory intelligence, supplier comms, and what changes after launch.",
    category: "Field notes",
    readTime: "7 min",
    date: "May 12, 2026",
    published: true,
  },
  {
    slug: "/blog/agency-scenario",
    title: "How an agency reclaimed a full senior week per month with AI",
    dek: "An illustrative Maxera scenario: how a custom AI workflow stack pulled 28 hours a week of senior team time out of repetitive client admin work, freeing the team for strategy instead of status emails.",
    category: "Field notes",
    readTime: "6 min",
    date: "May 11, 2026",
    published: true,
  },
  {
    slug: "/blog/stop-reading-about-ai",
    title: "Stop reading about AI. Start putting it to work.",
    dek: "Most owners we talk to have read every AI thread on LinkedIn and watched every YouTube tutorial. They’re more confused than when they started. Here’s the simpler way to think about it.",
    category: "Strategy",
    readTime: "6 min",
    date: "May 02, 2026",
    published: true,
  },
  {
    slug: "/blog/strategy-deck-consulting",
    title: "Why strategy-deck consulting rarely ships anything",
    dek: "The strategy-deck consultancy model has the wrong incentives baked in. A look at why advisory engagements stall, and what 'we deliver, we don’t just advise' actually changes.",
    category: "Method",
    readTime: "5 min",
    date: "Apr 21, 2026",
    published: false,
  },
  {
    slug: "/blog/front-desk-admin-work",
    title: "The four hours a day your front desk shouldn’t be doing",
    dek: "Missed-call follow-up, appointment confirmations, review chasing. The admin work that quietly eats half the team’s morning, and why it’s the cleanest place to start with AI.",
    category: "Field notes",
    readTime: "5 min",
    date: "Apr 03, 2026",
    published: false,
  },
  {
    slug: "/blog/ai-voice-agents",
    title: "What an AI voice agent actually does (and doesn’t)",
    dek: "A plain-language walkthrough of what voice agents handle, what they hand off, and the four mistakes most owners make when deploying them.",
    category: "Method",
    readTime: "7 min",
    date: "Mar 18, 2026",
    published: false,
  },
  {
    slug: "/blog/ai-tool-not-working",
    title: "Bought an AI tool that isn’t working? You’re not alone.",
    dek: "We hear this every week. Companies bought AI tools, never deployed them properly, and assumed AI doesn’t work for them. Here’s how to tell what’s worth saving.",
    category: "Strategy",
    readTime: "4 min",
    date: "Mar 02, 2026",
    published: false,
  },
  {
    slug: "/blog/built-by-us-owned-by-you",
    title: "Built by us, owned by you",
    dek: "Why we don’t host the systems we build, won’t lock you in, and hand over every piece of infrastructure at the end of the engagement.",
    category: "Operating",
    readTime: "5 min",
    date: "Feb 14, 2026",
    published: false,
  },
];
